Implement Jotai as state store + indicator component
IrisHub/SpaceBar pull request #143
Opened 2022-12-11 02:45 UTC by samjgorman

### Description of Changes
- Import Jotai as a state store
- Use Jotai to store communicator globally across the app
- Refactor components to read communicator from Jotai 
- Indicator component that reads from jotai state to determine num players in room

### Link to Issue
Link the appropriate GitHub Issue for this PR. You can link an issue by adding `closes #issue-number` to the PR message body.

### Testing Procedure
Demod to the team + tested across two windows

2022-12-16 06:28 UTC, shalins requested changes
Was looking over this PR mostly to understand the changes to the Communicator hook, but had some thoughts along the way so ended up doing a more comprehensive review. Overall, nice work introducing Jotai and moving Communicator to the top level! I'm requesting changes for now because of some of the reasons I've included in the comments below.

2022-12-16 06:28 UTC, shalins commented on src/network/communicatorAtomStore.ts
> +export default null;
```suggestion
```
I think we should enforce proper importing of the consts above instead of doing this.

2022-12-16 06:28 UTC, shalins commented on src/network/hooks/useInitializeCommunicator.ts
> + * @returns {CommunicatorRef} A reference to the Communicator.
I don't think this function returns a `CommunicatorRef`

2022-12-16 06:28 UTC, shalins commented on src/scene/players/Players.tsx
> +    communicator?.on('message', (data) => {
Nice side effect of using Jotai!

2022-12-16 06:28 UTC, shalins commented on src/scene/players/Players.tsx
> +      <UserPlayer listener={listenerRef} />
Useful simplification here!

2022-12-16 06:28 UTC, shalins commented on src/App.tsx
> +  useInitializeCommunicator(roomId);
Nice work promoting this to `App`

2022-12-16 06:29 UTC, shalins commented on src/App.tsx
> +import useInitializeCommunicator from './network/hooks/useInitializeCommunicator';
Update: after reading through the rest of code, I think it makes most sense just to update useCommunicator directly.

2022-12-18 05:17 UTC, samjgorman commented on src/network/hooks/useInitializeCommunicator.ts
> + * @returns {CommunicatorRef} A reference to the Communicator.
Nice catch!

2022-12-18 06:14 UTC, samjgorman commented on src/App.tsx
> +  const roomId = 'test_room_id';
Great idea! Done

2022-12-18 06:15 UTC, samjgorman commented on src/interface/VideoPlayer.tsx
> +
Nice catch-- not needed here!

2022-12-22 03:37 UTC, shalins commented on src/network/hooks/useInitializeCommunicator.ts
> +    console.log(
```suggestion
    console.warn(
```

2022-12-22 03:38 UTC, shalins commented on src/scene/players/Players.tsx
> +  useCommunicator({ onMedia: onMedia, onMessage: onMessage });
Cool change!

2022-12-22 03:40 UTC, shalins approved these changes

2022-12-22 03:56 UTC, merged