feat: Update player model
IrisHub/SpaceBar pull request #197
Opened 2023-04-01 22:01 UTC by kanyesthaker

### Description of Changes
This pull request updates the player model to use an off-the-shelf glTF from SketchFab. The purpose of this is twofold:

1. I hypothesizes that making the player model smaller and friendlier will make the space feel more comfortable and reduce the friction with using the mouse to move (i.e. if a player is a cube, rotating with the mouse feels like the whole body is rotating. But if the player is a sphere, maybe it will feel more like only the player's head is rotating, which feels more natural).
2. Changing the hitbox of the player to only exist where the camera is (not on all sides) preserves the "personal space bubble" feeling without the annoyance of having a large impassible object in the bar.

### Link to Issue
closes #189 

### Testing Procedure
Tested locally. Plan on doing joint testing session with Sam before merging.

2023-04-22 23:18 UTC, samjgorman requested changes
Awesome work here, left comments to see this get cleaned up a bit more and we'll be ready to merge!

2023-04-22 23:18 UTC, samjgorman commented on src/common/constants.ts
> +  static readonly playerSize: [number, number, number] = [1, 1, 0.125];
Nice bump in size -- noticed the improvement in live QA

2023-04-22 23:18 UTC, samjgorman commented on src/common/utils/models.ts
> +  model.quaternion.copy(params.quaternion);
Why do we do this?

2023-04-22 23:18 UTC, samjgorman commented on src/scene/players/PeerPlayer.tsx
> +/* eslint-disable react/display-name */
Can we avoid needing to disable this lint rule?

2023-04-22 23:18 UTC, samjgorman commented on src/scene/players/PeerPlayer.tsx
> +    console.log(`T: ${t.current}`);
👀 Let's remove these logs!

2023-04-22 23:18 UTC, samjgorman commented on src/scene/players/PeerPlayer.tsx
> +  const t = useRef<number>(0);
Need a more descriptive variable name here -- does this represent time?

2023-04-22 23:18 UTC, samjgorman commented on src/scene/players/PeerPlayer.tsx
>      // Position update
This comment isn't descriptive enough to be helpful -- remove or add a more descriptive comment that talks about how this adds a slight bobbing to the player model

2023-04-22 23:18 UTC, samjgorman commented on src/scene/players/PeerPlayer.tsx
> +  useEffect(() => {
Let's add a comment to this useEffect to describe what we're doing here

2023-04-23 17:45 UTC, kanyesthaker commented on src/common/utils/models.ts
> +  model.quaternion.copy(params.quaternion);
In case we want to be able to rotate the model

2023-04-23 18:37 UTC, samjgorman approved these changes
Looks good, looks like one point wasn't addressed but otherwise LGTM!

2023-04-23 18:37 UTC, samjgorman commented on src/scene/players/PeerPlayer.tsx
> +  useEffect(() => {
Don't think this was addressed?

2023-04-23 19:53 UTC, merged