feat: Add Jest and client-side smoke testing
IrisHub/SpaceBar pull request #230
Opened 2023-06-03 06:43 UTC by kanyesthaker

### Description of Changes
- Add Jest and `@react-three/test-renderer` as testing utilities
- Write basic smoke tests for the client with/without Three components
- Note that the React Three test renderer only works on children of the <Canvas />, so we will use traditional testing for the rest of the project

Note: I do get some warning related to using `ReactDOM.render` as part of the test due to deprecation between React 17 and 18. This should not impact functionality but can add noise. Open to suggestions. I also get a warning about using `act(...)`, even though I do not use the `await act` pattern anywhere; I believe this is because the React Fiber testing library may be outdated.

### Link to Issue
closes #228 

### Testing Procedure
- Wrote a smoke test for Scene that simply checks that the Scene component renders with nonzero elements
- Wrote a smoke test for a simple glTF that asserts that the glTF renders
![image](https://github.com/IrisHub/SpaceBar/assets/31911175/4c6f81ce-bcbe-4266-ba86-979d84f954a0)

2023-06-03 06:45 UTC, kanyesthaker commented on src/scene/models/__tests__/GLTFModel.test.tsx
> +    expect(allChildren.length).toEqual(1);
@samjgorman let me know if this is idiomatic, i.e. `toEqual` versus `toBe`

2023-06-04 06:04 UTC, samjgorman requested changes
Looking good! Just have some more requests to help set up jest in our application! 

1. Can you install `@types/jest `to our project's dependencies? This will help us write & type future jest tests
2. Let's create a barebones` jest.config.ts` file such that we'll have a place to modify & tweak jest settings as time goes on.  For now, we can just import the Jest defaults, like this...



````typescript

import type {Config} from 'jest';
import {defaults} from 'jest-config';

const config: Config = {
  moduleFileExtensions: [...defaults.moduleFileExtensions, 'mts'],
};

export default config;

````

3.  Mind creating a Notion doc or readme that documents the command that we can run to run these Jest tests?

2023-06-04 06:13 UTC, kanyesthaker commented on src/scene/__tests__/Scene.test.tsx
> +  it('should render some elements', async () => {
the intent behind this PR is to set up Jest and to add a smoke test to make sure that the _testing library_ itself is working. Smoke tests just do basic things like "ensure that the page does not crash when loaded" -- I'll leave the act of actually writing unit tests to a future PR.

2023-06-04 06:17 UTC, kanyesthaker commented on src/scene/__tests__/Scene.test.tsx
> +window.ResizeObserver = MockResizeObserver;
Without mocking ResizeObserver rendering `<Scene />` will fail with 
```
This browser does not support ResizeObserver out of the box. See: https://github.com/react-spring/react-use-measure/#resize-observer-polyfills
```
I believe the React Fiber `<Canvas />` component uses ResizeObserver by default. I didn't bother digging too deep.

2023-06-04 06:18 UTC, kanyesthaker commented on src/scene/__tests__/Scene.test.tsx
> +window.ResizeObserver = MockResizeObserver;
Actually yes -- the Fiber `<Canvas />` component uses `react-use-measure` which requires `ResizeObserver`, which is not available in our testing environment https://docs.pmnd.rs/react-three-fiber/api/canvas

2023-06-04 07:42 UTC, samjgorman approved these changes
Great job getting this test infra in!

2023-06-04 07:42 UTC, samjgorman commented on src/scene/__tests__/Scene.test.tsx
> +  it('should render some elements', async () => {
That's alright with me

2023-06-04 15:17 UTC, merged